// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcb3-S6fRo7t6Kgd1YFoVlTZm_PnMw0gE',
    appId: '1:58175682591:web:b806c6fc78d734f53e3d2a',
    messagingSenderId: '58175682591',
    projectId: 'to-do-app-10e5f',
    authDomain: 'to-do-app-10e5f.firebaseapp.com',
    storageBucket: 'to-do-app-10e5f.firebasestorage.app',
    measurementId: 'G-3PLW4EB415',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCT4mt5j2aXiugiiD7qu0SQmV2D420JXZc',
    appId: '1:58175682591:android:978173c4d97d21153e3d2a',
    messagingSenderId: '58175682591',
    projectId: 'to-do-app-10e5f',
    storageBucket: 'to-do-app-10e5f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoDL1bp4o-p6qCf7dQAnjO1dJZ1GahwGo',
    appId: '1:58175682591:ios:f22d369d17efd09d3e3d2a',
    messagingSenderId: '58175682591',
    projectId: 'to-do-app-10e5f',
    storageBucket: 'to-do-app-10e5f.firebasestorage.app',
    iosClientId: '58175682591-a93pqal1jjnfhtodq2fphltl0779pceq.apps.googleusercontent.com',
    iosBundleId: 'com.example.toDoAppFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoDL1bp4o-p6qCf7dQAnjO1dJZ1GahwGo',
    appId: '1:58175682591:ios:f22d369d17efd09d3e3d2a',
    messagingSenderId: '58175682591',
    projectId: 'to-do-app-10e5f',
    storageBucket: 'to-do-app-10e5f.firebasestorage.app',
    iosClientId: '58175682591-a93pqal1jjnfhtodq2fphltl0779pceq.apps.googleusercontent.com',
    iosBundleId: 'com.example.toDoAppFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcb3-S6fRo7t6Kgd1YFoVlTZm_PnMw0gE',
    appId: '1:58175682591:web:9e19e82275c5fe813e3d2a',
    messagingSenderId: '58175682591',
    projectId: 'to-do-app-10e5f',
    authDomain: 'to-do-app-10e5f.firebaseapp.com',
    storageBucket: 'to-do-app-10e5f.firebasestorage.app',
    measurementId: 'G-7HGW9RF2HV',
  );

}